### PR TITLE
Fixed Leaderboard

### LINKED ISSUE #345: On clicking Leaderboard on the boss website throws error
BOSS - Google Chrome 5_24_2020 2_22_01 AM
 
This is the issue that its throwing and it needs a quick fix 
@hereisnaman please review this error and assign bounties to this issue so that I can start working on it

### PR DESCRIPTION
**Pull request by prathambatra**
Signed-off-by: prathambatra <batrapratham999@gmail.com>
fixes #345

### CODE REVIEW

File: routes/root.js [hunk 1]
```diff
@@ -43,6 +43,9 @@ route.get('/leaderboard/:year?', async (req, res) => {
     let { year } = req.params
```
Comment (hereisnaman) [inline routes/root.js:43]: `let { year = '2020' } = req.params`

just do this here.

Comment (hereisnaman) [reply routes/root.js:43]: don't forget to run and test the solution.

Comment (prathambatra) [reply routes/root.js]: done..
