### PR TITLE
fix: add a middleware to check if user is claimer of claim

### LINKED ISSUE #280: Don't allow Unauthorized editing/deleting of Claims
Anyone can edit/delete anyone's Claims right now (they just need to be logged in in github). 
https://boss.codingblocks.com/claims/863/edit
Claims should allowed to edit by the person who claimed it

### PR DESCRIPTION
**Pull request by prabalsingh24**
fixes #280

### CODE REVIEW

**Comment by prabalsingh24** [comment]
Screenshot from 2020-05-18 21-36-20

File: utils/auth.js [hunk 1]
```diff
@@ -80,5 +81,21 @@ module.exports = {
...
+  ensureUserCanEdit(req, res, next) {
+      // check if the user is claimer of the claim
+      du.getClaimById(req.params.id)
+          .then(claim => {
+              if (!claim) throw new Error('No claim found')
+              if (claim.user === req.user.usergithub.username) {
+                  next()
+              }
+              else {
+                  res.render('error', {error: 'You are not the claimer of this claim.'})
```
Comment (hereisnaman) [inline utils/auth.js:94]: Make it "You are not authorized to edit this claim."
