### PR TITLE
Fixed NaN values in datautils.getCounts

### LINKED ISSUE #177: Fix stats page
Screen Shot 2019-05-16 at 1 57 39 PM

### PR DESCRIPTION
**Pull request by nikhilhassija**
Fixes #177

### CODE REVIEW

File: utils/datautils.js [hunk 1]
```diff
@@ -121,13 +121,13 @@ function getCounts() {
...
     );
-    if (Number.isNaN(accepted)) {
-        accepted = 0;
-    }
-    if (Number.isNaN(totalclaimed)) {
-        totalclaimed = 0;
-    }
-    return Promise.all([participants, claims, accepted, totalclaimed]);
+
+    var filterNaN = (data) => Number.isNaN(data)? 0 : data;
```
Comment (abhishek97) [inline utils/datautils.js]: let's use `||` instead of `isNaN` to check for all falsy and NaN values

Comment (nikhilhassija) [reply utils/datautils.js]: Fixed in latest commit.
